# ansible/hardening.yml
- name: Harden RHEL 9 Server to CIS Benchmark
  hosts: all
  become: true
  gather_facts: true

  roles:
    - role: ansible-lockdown.RHEL9-CIS
      tags:
        - level2-server

- name: Final Image Cleanup
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Remove the temporary packer user
      ansible.builtin.user:
        name: packer
        state: absent
        remove: true

    - name: Remove the packer sudoers file
      ansible.builtin.file:
        path: /etc/sudoers.d/packer
        state: absent
