---
- name: Apply CIS RHEL 9 Hardening
  hosts: all
  become: yes
  vars_files:
    - group_vars/all/cis_settings.yaml

  tasks:
    # 1.1 Filesystem Configuration
    - name: 1.1.1 Ensure mounting of cramfs filesystems is disabled
      lineinfile:
        path: /etc/modprobe.d/cis.conf
        line: "install cramfs /bin/true"
        create: yes
        state: present

    - name: 1.1.2 Ensure mounting of squashfs filesystems is disabled
      lineinfile:
        path: /etc/modprobe.d/cis.conf
        line: "install squashfs /bin/true"
        create: yes
        state: present

    - name: 1.1.3 Ensure mounting of udf filesystems is disabled
      lineinfile:
        path: /etc/modprobe.d/cis.conf
        line: "install udf /bin/true"
        create: yes
        state: present

    # 1.2 Configure Software Updates
    - name: 1.2.1 Ensure GPG keys are configured
      command: rpm -q gpg-pubkey
      register: gpg_keys
      changed_when: false
      failed_when: false

    - name: 1.2.2 Ensure package manager repositories are configured
      command: yum repolist
      register: repo_list
      changed_when: false
      failed_when: false

    # 1.3 Secure Boot Settings
    - name: 1.3.1 Ensure permissions on bootloader config are configured
      file:
        path: /boot/grub2/grub.cfg
        owner: root
        group: root
        mode: '0600'
        state: file

    - name: 1.3.2 Ensure bootloader password is set
      command: grep "^GRUB2_PASSWORD" /boot/grub2/user.cfg
      register: bootloader_password
      changed_when: false
      failed_when: false
      ignore_errors: true

    # 1.4 Additional Process Hardening
    - name: 1.4.1 Ensure core dumps are restricted
      lineinfile:
        path: /etc/security/limits.conf
        line: "* hard core 0"
        state: present

    - name: 1.4.2 Ensure address space layout randomization (ASLR) is enabled
      sysctl:
        name: kernel.randomize_va_space
        value: '2'
        state: present
        reload: yes

    # 1.5 Mandatory Access Control
    - name: 1.5.1 Ensure SELinux is installed
      package:
        name: libselinux
        state: present

    - name: 1.5.2 Ensure SELinux is not disabled in bootloader configuration
      replace:
        path: /etc/default/grub
        regexp: 'selinux=0'
        replace: ''

    - name: 1.5.3 Ensure SELinux policy is configured
      lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUXTYPE='
        line: 'SELINUXTYPE=targeted'
        state: present

    - name: 1.5.4 Ensure the SELinux mode is enforcing
      lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: 'SELINUX=enforcing'
        state: present

    # 2.1 Special Purpose Services
    - name: 2.1.1 Remove unnecessary services
      package:
        name: "{{ cis_remove_packages }}"
        state: absent

    - name: 2.1.2 Disable unnecessary services
      service:
        name: "{{ item }}"
        state: stopped
        enabled: no
      with_items: "{{ cis_disable_services }}"
      ignore_errors: yes

    # 3.1 Network Parameters (Host Only)
    - name: 3.1.1 Ensure IP forwarding is disabled
      sysctl:
        name: net.ipv4.ip_forward
        value: '0'
        state: present
        reload: yes

    - name: 3.1.2 Ensure packet redirect sending is disabled
      sysctl:
        name: net.ipv4.conf.all.send_redirects
        value: '0'
        state: present
        reload: yes
      with_items:
        - net.ipv4.conf.all.send_redirects
        - net.ipv4.conf.default.send_redirects

    # 3.2 Network Parameters (Host and Router)
    - name: 3.2.1 Ensure source routed packets are not accepted
      sysctl:
        name: "{{ item }}"
        value: '0'
        state: present
        reload: yes
      with_items:
        - net.ipv4.conf.all.accept_source_route
        - net.ipv4.conf.default.accept_source_route

    - name: 3.2.2 Ensure ICMP redirects are not accepted
      sysctl:
        name: "{{ item }}"
        value: '0'
        state: present
        reload: yes
      with_items:
        - net.ipv4.conf.all.accept_redirects
        - net.ipv4.conf.default.accept_redirects

    # 3.3 Firewall Configuration
    - name: 3.3.1 Ensure firewalld is installed
      package:
        name: firewalld
        state: present
      when: cis_enable_firewalld

    - name: 3.3.2 Ensure firewalld service is enabled and running
      service:
        name: firewalld
        state: started
        enabled: yes
      when: cis_enable_firewalld

    - name: 3.3.3 Ensure default zone is set
      command: firewall-cmd --set-default-zone={{ cis_firewall_default_zone }}
      when: cis_enable_firewalld
      changed_when: false

    # 4.1 Configure System Accounting (auditd)
    - name: 4.1.1 Ensure auditd is installed
      package:
        name: audit
        state: present

    - name: 4.1.2 Ensure auditd service is enabled and running
      service:
        name: auditd
        state: started
        enabled: yes

    - name: 4.1.3 Configure auditd max log file size
      lineinfile:
        path: /etc/audit/auditd.conf
        regexp: '^max_log_file\s*='
        line: "max_log_file = {{ cis_max_log_file_size }}"
        state: present

    # 5.1 Configure cron
    - name: 5.1.1 Ensure cron daemon is enabled and running
      service:
        name: crond
        state: started
        enabled: yes

    - name: 5.1.2 Ensure permissions on /etc/crontab are configured
      file:
        path: /etc/crontab
        owner: root
        group: root
        mode: '0600'
        state: file

    # 5.2 SSH Server Configuration
    - name: 5.2.1 Ensure permissions on SSH private host key files are configured
      file:
        path: /etc/ssh
        owner: root
        group: root
        mode: '0600'
        state: directory
        recurse: yes

    - name: 5.2.2 Ensure SSH Protocol is set to 2
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^Protocol'
        line: 'Protocol 2'
        state: present

    - name: 5.2.3 Ensure SSH LogLevel is appropriate
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^LogLevel'
        line: 'LogLevel INFO'
        state: present

    - name: 5.2.4 Ensure SSH X11 forwarding is disabled
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^X11Forwarding'
        line: 'X11Forwarding no'
        state: present

    - name: 5.2.5 Ensure SSH MaxAuthTries is set to 4 or less
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^MaxAuthTries'
        line: 'MaxAuthTries 4'
        state: present

    - name: 5.2.6 Ensure SSH IgnoreRhosts is enabled
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^IgnoreRhosts'
        line: 'IgnoreRhosts yes'
        state: present

    - name: 5.2.7 Ensure SSH HostbasedAuthentication is disabled
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^HostbasedAuthentication'
        line: 'HostbasedAuthentication no'
        state: present

    - name: 5.2.8 Ensure SSH root login is disabled
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
        state: present

    - name: 5.2.9 Ensure SSH PermitEmptyPasswords is disabled
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitEmptyPasswords'
        line: 'PermitEmptyPasswords no'
        state: present

    - name: 5.2.10 Ensure SSH PermitUserEnvironment is disabled
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitUserEnvironment'
        line: 'PermitUserEnvironment no'
        state: present

    # 5.3 Configure PAM
    - name: 5.3.1 Ensure password creation requirements are configured
      lineinfile:
        path: /etc/security/pwquality.conf
        regexp: '^minlen'
        line: "minlen = {{ cis_password_min_length }}"
        state: present

    - name: 5.3.2 Ensure lockout for failed password attempts is configured
      lineinfile:
        path: /etc/pam.d/password-auth
        line: "auth required pam_faillock.so preauth audit silent deny={{ cis_failed_password_attempts }} unlock_time=900"
        state: present

    # 5.4 User Accounts and Environment
    - name: 5.4.1 Set Shadow Password Suite Parameters
      lineinfile:
        path: /etc/login.defs
        regexp: "^{{ item.param }}"
        line: "{{ item.param }} {{ item.value }}"
        state: present
      with_items:
        - { param: "PASS_MAX_DAYS", value: "{{ cis_password_max_days }}" }
        - { param: "PASS_MIN_DAYS", value: "{{ cis_password_min_days }}" }
        - { param: "PASS_WARN_AGE", value: "{{ cis_password_warn_age }}" }

    - name: 5.4.2 Ensure default user umask is configured
      lineinfile:
        path: /etc/profile.d/cis.sh
        line: "umask {{ cis_umask_default }}"
        create: yes
        state: present

    # 6.1 System File Permissions
    - name: 6.1.1 Audit system file permissions
      command: rpm -Va --nomtime --nosize --nomd5 --nolinkto
      register: rpm_verify
      changed_when: false
      failed_when: false

    # 6.2 User and Group Settings
    - name: 6.2.1 Ensure password fields are not empty
      command: awk -F':' '($2 == "" ) { print $1 " does not have a password "}' /etc/shadow
      register: empty_password
      changed_when: false
      failed_when: false

    # Final restart of services
    - name: Restart sshd service
      service:
        name: sshd
        state: restarted

    - name: Restart auditd service
      service:
        name: auditd
        state: restarted